---
title: My Jira Dashboard
refreshInterval: 60s
grid:
  columns: 2
  rows: 5
cells:
  - title: Env Epics
    query: filter=17201
    template: epics.gohtml
    position:
      row: 1
      col: 1
  - title: Open Environment Issues
    query: filter=17203
    template: issues.gohtml
    position: { row: 1, col: 2 }
  - title: Two Dimensional Open Environment Issues
    query: filter=17203
    template: env_issues.gohtml
    position: { row: 2, col: 1 }
  - title: Top 3 most Issues
    query: filter=17203
    template: podium.gohtml
    position: { row: 2, col: 2 }
  - title: "Issue Statistics: Open Environment Issues (Assignee)"
    query: filter=17203
    template: assignees.gohtml
    position: { row: 3, col: 1, colSpan: 2 }
customization:
  grid:
    gap: 1rem
    padding: 0rem
    marginTop: 0rem
  card:
    borderColor: "#ddd"
    padding: 1rem
    backgroundColor: "#fff"
    borderRadius: 0.5rem
    boxShadow: 0 2px 4px rgba(0, 0, 0, 0.05)
  header:
    align: center
    marginBottom: 0.5rem
  footer:
    marginTop: 1rem
  font:
    family: "Segoe UI, sans-serif"
    size: 16px
