---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes/
configMapGenerator:
  - name: jirapanel-config
    files:
      - config.yaml
  - name: jirapanel-templates
    files:
      - templates/assignees.gohtml
      - templates/env_issues.gohtml
      - templates/epics.gohtml
      - templates/functions.gohtml
      - templates/issues.gohtml
